config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  #######API#########
  #https::/api.coursemate.io/v1/users

  constraints subdomain: 'api' do 
    namespace :api, defaults: {format: :json}, path: '/' do         
      namespace :v1 do
        resources :auth_tokens, only: [:create]
        resources :users, only: [:index]
      end
    end
  end

  authenticated :user do
    root "groups#show_from_my_university", as: :authenticated_root
  end

  root "groups#index"

  devise_for :users, :path => 'account', :path_names => { :edit => "edit_account" }

  # SIDEKIQ
  authenticate :user, lambda { |u| u.is_master? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'account/edit_profile', to: 'users#edit'

  resources :users, only: [:index, :show, :update] do 
    member do 
      get 'questions'
      get 'answers'
      get 'groups'
    end
  end

  resources :notifications, only: [:index] do
    member do
      patch 'mark_read'
    end
    collection do
      get 'top_notifications'
    end
  end

  resources :questions, shallow: true do
    resources :comments, except: [:new, :show]
    resources :answers, except: [:new, :show]
    member do 
      delete 'likes', to: 'likes#destroy', defaults: { type: "question" }
      post 'likes', to: 'likes#create', defaults: { type: "question" }
    end
  end

  resources :course_auto_completes, only: [:index]

  resources :answers, only: [], shallow: true do
    resources :comments, except: [:new, :show]
    member do 
      delete 'likes', to: 'likes#destroy', defaults: { type: "answer" }
      post 'likes', to: 'likes#create', defaults: { type: "answer" }
    end
  end

  resources :groups, shallow: true do 
    resources :comments, except: [:new, :show]
    member do
      delete 'enrollments', to: 'group_enrollments#destroy'
      post 'enrollments', to: 'group_enrollments#create'
    end
  end

  namespace :groups do 
    resources :cancelations, only: [] do 
      member do 
        patch 'cancel'
      end
    end
  end

  get 'subscriptions/:id/unsubscribe', to: 'subscriptions#unsubscribe', as: 'unsubscribe', id: "{{SECRET_TOKEN}}"

  resources :user_courses, only: [:create, :destroy]

  constraints course: /[\S\s]+/, university: /[\S\s]+/ do #necessary to pass the domain and course params as they are, otherwise queensu.ca will be passed as queenu only, this constraint escapes special chars.
    get 'groups/courses/:course', to: 'groups#show_from_course', as: 'show_groups_in_course'
    get 'questions/courses/:course', to: 'questions#show_from_course', as: 'show_questions_in_course'
    get 'groups/universities/:university', to: 'groups#show_from_university', as: 'show_groups_in_university'
    get 'questions/universities/:university', to: 'questions#show_from_university', as: 'show_questions_in_university'
  end

  namespace :questions do 
    #necessary to pass the domain and course params as they are, otherwise queensu.ca will be passed as queenu only, this constraint escapes special chars.
    constraints course: /[\S\s]+/, university: /[\S\s]+/ do
      get 'unanswered/:course', to: 'unanswered#index', as: 'unanswered'
    end
  end

end

app/models/question.rb
class Question < ActiveRecord::Base

  default_scope { order(id: :desc) }

  belongs_to :user
  has_many :answers
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :university, foreign_key: 'university_domain', required: true
  belongs_to :course, foreign_key: [:course_name, :university_domain], required: true

  validates :title, presence: true
  validates :body, presence: true

end

app/controllers/questions/unanswered_controller.rb
class Questions::UnansweredController < ApplicationController

  def index
    @course = Course.find(params[:course])
    @questions = @course.question_indices.unanswered.paginate(per_page: 5, page: params[:page]).includes(:user)
    render :index
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy, :show_from_my_university]
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :authorize, only: [:edit, :update, :destroy]
  before_action :set_autocomplete, only: [:new, :create]

  def index
    #QuestionIndex is a view defined in db/views
    @questions    = QuestionIndex.paginate(per_page: 5, page: params[:page]).includes(:user)
    @universities = University.joins(:questions).distinct
  end

  def show
    #QuestionShow is a view defined in db/views
    @question = QuestionShow.find(params[:id])
    @comments = @question.comments.includes(:user).order('id ASC')
    @answers  = @question.answer_shows.includes(:user, {comments: :user}).order('id ASC')
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def create
    #courses are unique, find existing or create new one
   course = Course.where(
      name: params[:course_name].upcase.strip.gsub(/ +/,""),
      university_domain: params[:university_domain],
   ).first_or_create

    @question      = course.questions.new(question_params)
    @question.user = current_user

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully published.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: "Question successfully updated." }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @question.destroy
        format.html { redirect_to authenticated_root_path, notice: 'Questions was deleted.' }
      else
        format.html {
          flash[:alert] = 'Answered questions cannot be deleted.'
          render :show
        }
      end
    end
  end

  def show_from_course
    @course     = Course.find(params[:course])
    @university = @course.university
    @questions  = @course.question_indices.paginate(per_page: 5, page: params[:page]).includes(:user)
    render :show_with_course
  end

  def show_from_my_university
    @university = current_user.university
    @questions  = @university.question_indices.paginate(per_page: 5, page: params[:page]).includes(:user)
    @courses    = Course.joins(:questions).where(university_domain: @university.domain).distinct
    render :show_from_university
  end

  def show_from_university
   @university   = University.find(params[:university])
   @courses      = Course.joins(:questions).where(university_domain: @university.domain).distinct
   @questions    = @university.question_indices.paginate(per_page: 5, page: params[:page]).includes(:user)
  end

  private

    def question_params
      params.require(:question).permit(:title, :body)
    end

    def set_question
      @question = Question.find(params[:id])
    end

    def set_autocomplete
      @university = current_user.university
      @courses = @university.courses.pluck(:name)
    end

    def authorize
      unless @question.user == current_user
        flash[:alert] = "You are not allowed to edit someone else's question."
        redirect_to @question
      end
    end

end

app/views/questions/_form.html.haml
=fields_for :question do |g_fields|
  =label_tag 'Title'
  %br
  =g_fields.text_field :title, class: 'form-control', placeholder: "Enter a title for the question"
  %br
  =label_tag 'Body'
  %br
  #wmd-button-bar-body
  =g_fields.text_area :body, id: 'wmd-input-body', class: 'wmd-input form-control', placeholder: "Enter the question body..", rows: 10
  #wmd-preview-body.wmd-preview

app/views/questions/_link.html.haml
.link
  .card.frow{id: "Question#{question.id}"}
    .profile-pic.small
      =link_to(image_tag("avatar-50.png", alt: "profile pic", class: "img-circle"), user_path(question.user))
    .fcol
      .frow.bottom-space
        %h4.title
          =link_to("#{question.title}", question_path(question))
        .time.grey
          =local_relative_time(question.created_at, type: 'time-or-date')

      .frow
        .tags
          -tag = question.tags.first
          =link_to("#{tag.university}", show_with_university_tag_path(tag.university), class: "btn btn-xs btn-info", role: "button")
          =link_to("#{tag.name}", show_with_tag_path(tag.id, tag.name.gsub(" ", "-")), class: "btn btn-xs btn-info", role: "button")
          -if question.num_answers == 0
            =link_to("unanswered", unanswered_with_tag_path(tag.id, tag.name.gsub(" ", "-")), class: "btn btn-xs btn-success", role: "button")
        .votes
          =render 'likes/like', likeable: question, path: question_likes_path(question, Like.new)

app/views/questions/_question.html.haml
.link
  .card.frow{id: "Question#{question.id}"}
    .profile-pic.size-30px
      = render 'partials/profile_picture', user: question.user, size: :small
    .fcol
      .frow.bottom-space
        %h4.title
          =link_to("#{question.title}", question_path(question))
        .time.grey
          =local_relative_time(question.created_at, type: 'time-or-date')

      .frow
        .tags
          
          =link_to("#{question.university_name}", show_questions_in_university_path(question.university_domain), class: "btn btn-xs btn-info", role: "button")
          =link_to("#{question.course_name}", show_questions_in_course_path(question.course_url), class: "btn btn-xs btn-info", role: "button")
          -if question.num_answers == 0
            =link_to("unanswered", questions_unanswered_path(question.course_url), class: "btn btn-xs btn-success", role: "button")
        //.votes
        //=render 'likes/like', likeable: question, path: question_likes_path(question)

app/views/questions/_question_card.html.haml
.card.frow.header
  %h4.title
    =@question.title
  .time.grey
    =local_relative_time(@question.created_at, type: 'time-or-date')

.card.frow.main
  .profile-pic.size-40px
    = render 'partials/profile_picture', user: @question.user, size: :small
  .fcol
    .body
      :markdown
        #{@question.body}
    .frow.bottom-space
      .tags
        =link_to("#{@question.university_name}", show_questions_in_university_path(@question.university_domain), class: "btn btn-xs btn-info", role: "button")
        =link_to("#{@question.course_name}", show_questions_in_course_path(@question.course_url), class: "btn btn-xs btn-info", role: "button")
        
    .frow
      .likeable-owner
        - if @question.user_id
          %span.grey asked by:
          =link_to(" " + @question.user.username, user_path(@question.user))
          %i.fa.fa-trophy.fa-lg.left-space
          ="+" + @question.user_score.to_s
      .votes
        =render 'likes/like', likeable: @question, path: likes_question_path(@question)
    -if owner @question
      .frow
        .edit-post
          =link_to("Edit", edit_question_path(@question))
          - if @question.num_answers == 0
            =link_to("Delete", question_path(@question), method: :delete)
          -else
            =link_to("Delete", '#', data: {toggle: "popover", content: "Questions that have answers can't be deleted, people invested effort in answering them."})

app/views/questions/edit.html.haml
.question-form
  %h4 Edit Question
  -if @question.errors.any?
    %ul.alert.alert-danger
      .container
        -@question.errors.full_messages.each do |msg|
          %li
            =msg
  =form_tag(question_path(@question.id), method: :patch, class: 'form-group') do
    =render 'form'
    %br
    =submit_tag 'Update Question', class: 'btn btn-primary'

app/views/questions/index.html.haml
%h4 Universities
.frow
  %span.universities
    -@universities.each do |u|        
      =link_to("#{u.name}", show_questions_in_university_path(u) , class: "btn btn-xs btn-info", role: "button")
  .new-question-button
    =link_to 'New Question', new_question_path, class: 'btn btn-primary'
%h4 Questions

=render partial: 'questions/question', collection: @questions
=will_paginate @questions, renderer: BootstrapPagination::Rails

app/views/questions/new.html.haml
.question-form
  %h4 New Question
  -if @question.errors.any?
    %ul.alert.alert-danger
      .container
        -@question.errors.full_messages.each do |msg|
          %li
            =msg
  =form_tag(questions_path, method: :post, class: 'form-group') do
    =label_tag 'University'
    %br
    //preselected university: on new page, it's the current user's university, on re-render after validation fails, it's the groups university 
    =select_tag :university_domain, options_from_collection_for_select(University.all, "domain", "name",@question.try(:university_domain) || @university.domain), class: 'form-control', id: 'university_select'
    %br
    =label_tag 'Course'
    %br
    =text_field_tag :course_name, nil, class: 'typeahead form-control', autocomplete: 'off', placeholder: "Enter a course name and number without spaces or special characters (e.g. HIST121) ...", data: { autocomplete_course: @courses }, id: 'question_courses'
    %br
    =render 'form'
    %br
    =submit_tag 'Publish Question', class: 'btn btn-primary'

app/views/questions/show.html.haml
.question-show
  .question{id: "Question#{@question.id}"}
    = render 'questions/question_card'
    .comments
      .ExistingComments
        =render @comments

      - if user_signed_in?
        =render 'comments/form', verb: :post, path: question_comments_path(@question)

  .existing-answers
    =render partial: 'answers/answer', collection: @answers

  .frow
    - if user_signed_in?
      .profile-pic.size-40px.standalone.new
        = render 'partials/profile_picture', user: current_user, size: :small
      .new-answer
        = form_tag(question_answers_path(@question), method: :post, class: 'form-group', remote: true) do
          =render 'answers/form'
          %span.help-block.has-error.errors
          %br
          =submit_tag 'Post Answer', class: 'btn btn-primary'
          
    - else
      .profile-pic.size-40px.standalone
        =image_tag("avatar.jpg", alt: "profile pic", class: "img-circle")
      .login-to-answer
        Log in to contribute your answer!

app/views/questions/show_from_university.html.haml
%h3
  =@university.name
.frow
  %span.courses
    %h4 Courses
    -@courses.each do |c|
      =link_to("#{c.name}", show_questions_in_course_path(c), class: "btn btn-xs btn-info", role: "button")
  .new-group-button
    =link_to "New Question", new_question_path, class: 'btn btn-primary'
%h4 Questions

=render partial: 'questions/question', collection: @questions
=will_paginate @questions, renderer: BootstrapPagination::Rails

app/views/questions/show_with_course.html.haml
.frow.subheader
  .info
    %h4
      =@course.name
      %br
      %small
        =@university.name
  .new-group-button
    =link_to 'New Question', new_question_path, class: 'btn btn-primary'

=render partial: 'questions/question', collection: @questions
=will_paginate @questions, renderer: BootstrapPagination::Rails

app/views/questions/unanswered_with_tag.html.haml
%h4
  =@tag.name + " (unanswered)"
  %br
  %small
    =@tag.university

=render @unanswered_questions
=will_paginate @unanswered_questions, renderer: BootstrapPagination::Rails