config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  #######API#########
  #https::/api.coursemate.io/v1/users

  constraints subdomain: 'api' do 
    namespace :api, defaults: {format: :json}, path: '/' do         
      namespace :v1 do
        resources :auth_tokens, only: [:create]
        resources :users, only: [:index]
      end
    end
  end

  authenticated :user do
    root "groups#show_from_my_university", as: :authenticated_root
  end

  root "groups#index"

  devise_for :users, :path => 'account', :path_names => { :edit => "edit_account" }

  # SIDEKIQ
  authenticate :user, lambda { |u| u.is_master? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'account/edit_profile', to: 'users#edit'

  resources :users, only: [:index, :show, :update] do 
    member do 
      get 'questions'
      get 'answers'
      get 'groups'
    end
  end

  resources :notifications, only: [:index] do
    member do
      patch 'mark_read'
    end
    collection do
      get 'top_notifications'
    end
  end

  resources :questions, shallow: true do
    resources :comments, except: [:new, :show]
    resources :answers, except: [:new, :show]
    member do 
      delete 'likes', to: 'likes#destroy', defaults: { type: "question" }
      post 'likes', to: 'likes#create', defaults: { type: "question" }
    end
  end

  resources :course_auto_completes, only: [:index]

  resources :answers, only: [], shallow: true do
    resources :comments, except: [:new, :show]
    member do 
      delete 'likes', to: 'likes#destroy', defaults: { type: "answer" }
      post 'likes', to: 'likes#create', defaults: { type: "answer" }
    end
  end

  resources :groups, shallow: true do 
    resources :comments, except: [:new, :show]
    member do
      delete 'enrollments', to: 'group_enrollments#destroy'
      post 'enrollments', to: 'group_enrollments#create'
    end
  end

  namespace :groups do 
    resources :cancelations, only: [] do 
      member do 
        patch 'cancel'
      end
    end
  end

  get 'subscriptions/:id/unsubscribe', to: 'subscriptions#unsubscribe', as: 'unsubscribe', id: "{{SECRET_TOKEN}}"

  resources :user_courses, only: [:create, :destroy]

  constraints course: /[\S\s]+/, university: /[\S\s]+/ do #necessary to pass the domain and course params as they are, otherwise queensu.ca will be passed as queenu only, this constraint escapes special chars.
    get 'groups/courses/:course', to: 'groups#show_from_course', as: 'show_groups_in_course'
    get 'questions/courses/:course', to: 'questions#show_from_course', as: 'show_questions_in_course'
    get 'groups/universities/:university', to: 'groups#show_from_university', as: 'show_groups_in_university'
    get 'questions/universities/:university', to: 'questions#show_from_university', as: 'show_questions_in_university'
  end

  namespace :questions do 
    #necessary to pass the domain and course params as they are, otherwise queensu.ca will be passed as queenu only, this constraint escapes special chars.
    constraints course: /[\S\s]+/, university: /[\S\s]+/ do
      get 'unanswered/:course', to: 'unanswered#index', as: 'unanswered'
    end
  end

end

app/views/partials/_errors.html.haml
- errors = resource.errors[field]
- if errors.any?
  = field_name + " " + errors[0]

app/views/partials/_menu.html.haml
.menu
  %nav.navbar.navbar-default.navbar-static-top
    .container-fluid
      .navbar-header
        %button.navbar-toggle.collapsed{type: "button", aria_expanded: "false", data: {toggle: "collapse", target: "#navbar"}}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        
        =image_tag("logo.png", alt: "site logo", class: "navbar-brand icon")
        =link_to("Coursemate", root_path, class: "navbar-brand title")
        
      .collapse.navbar-collapse#navbar
        %ul.nav.navbar-nav
          - if user_signed_in?
            %li{class: (params[:controller] == 'groups' ? "active-link" : "")}
              = link_to 'Groups', show_groups_in_university_path(current_user.university.id)
            %li{class: (params[:controller] == 'questions' ? "active-link" : "")}
              = link_to 'Questions', show_questions_in_university_path(current_user.university.id)
          - else
            %li{class: (params[:controller] == 'groups' ? "active-link" : "")}
              = link_to 'Groups', root_path
            %li{class: (params[:controller] == 'questions' ? "active-link" : "")}
              = link_to 'Questions', questions_path

          -if user_signed_in?
            %li.dropdown.notifications
              %a.dropdown-togggle{id: "nav-profile", href: "/notifications/top_notifications", role: "button", aria: {haspopup: "true", expanded: "false"}, data: {toggle: "dropdown", remote: true}}
                Notifications
                %span.badge.alert-danger
                  =current_user.unread_notification_count
              %ul.dropdown-menu.notifications
                //index.js.erb will be rendered here on click

        %ul.nav.navbar-nav.navbar-right
          -if user_signed_in?
            %li.dropdown
              %a.dropdown-togggle.profile-dropdown{id: "nav-profile", href: "#", role: "button", aria: {haspopup: "true", expanded: "false"}, data: {toggle: "dropdown"}}
                .profile-pic.size-35px
                  = render 'partials/profile_picture', user: current_user, size: :small
                %span.caret
              %ul.dropdown-menu.dropdown-menu-right
                %li.dropdown-header
                  Logged in as
                  .strong
                    =current_user.username_was
                %li.divider{role: "separator"}
                %li
                  =link_to('My Profile', user_path(current_user))
                %li.divider{role: "separator"}
                %li
                  =link_to("Profile Settings", account_edit_profile_path)
                %li
                  =link_to("Account Settings", edit_user_registration_path)
                %li.divider{role: "separator"}
                %li
                  =link_to("Log Out", destroy_user_session_path, method: :delete)
          - else
            %li
              = link_to "Sign up", new_user_registration_path
            %li
              = link_to("Log in", new_user_session_path)

app/views/partials/_profile_picture.html.haml
- if user && user.avatar_url.present?
  = image_tag user.avatar_url(size), class: 'img-circle', alt: 'Profile Picure'
- else
  - letter = user && user.username.first.match(/^[[:alpha:]]$/) ? user.username.first.upcase : '?'
  .letter-picture.text-center.img-circle{class: letter}
    = letter