config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  #######API#########
  #https::/api.coursemate.io/v1/users

  constraints subdomain: 'api' do 
    namespace :api, defaults: {format: :json}, path: '/' do         
      namespace :v1 do
        resources :auth_tokens, only: [:create]
        resources :users, only: [:index]
      end
    end
  end

  authenticated :user do
    root "groups#show_from_my_university", as: :authenticated_root
  end

  root "groups#index"

  devise_for :users, :path => 'account', :path_names => { :edit => "edit_account" }

  # SIDEKIQ
  authenticate :user, lambda { |u| u.is_master? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'account/edit_profile', to: 'users#edit'

  resources :users, only: [:index, :show, :update] do 
    member do 
      get 'questions'
      get 'answers'
      get 'groups'
    end
  end

  resources :notifications, only: [:index] do
    member do
      patch 'mark_read'
    end
    collection do
      get 'top_notifications'
    end
  end

  resources :questions, shallow: true do
    resources :comments, except: [:new, :show]
    resources :answers, except: [:new, :show]
    member do 
      delete 'likes', to: 'likes#destroy', defaults: { type: "question" }
      post 'likes', to: 'likes#create', defaults: { type: "question" }
    end
  end

  resources :course_auto_completes, only: [:index]

  resources :answers, only: [], shallow: true do
    resources :comments, except: [:new, :show]
    member do 
      delete 'likes', to: 'likes#destroy', defaults: { type: "answer" }
      post 'likes', to: 'likes#create', defaults: { type: "answer" }
    end
  end

  resources :groups, shallow: true do 
    resources :comments, except: [:new, :show]
    member do
      delete 'enrollments', to: 'group_enrollments#destroy'
      post 'enrollments', to: 'group_enrollments#create'
    end
  end

  namespace :groups do 
    resources :cancelations, only: [] do 
      member do 
        patch 'cancel'
      end
    end
  end

  get 'subscriptions/:id/unsubscribe', to: 'subscriptions#unsubscribe', as: 'unsubscribe', id: "{{SECRET_TOKEN}}"

  resources :user_courses, only: [:create, :destroy]

  constraints course: /[\S\s]+/, university: /[\S\s]+/ do #necessary to pass the domain and course params as they are, otherwise queensu.ca will be passed as queenu only, this constraint escapes special chars.
    get 'groups/courses/:course', to: 'groups#show_from_course', as: 'show_groups_in_course'
    get 'questions/courses/:course', to: 'questions#show_from_course', as: 'show_questions_in_course'
    get 'groups/universities/:university', to: 'groups#show_from_university', as: 'show_groups_in_university'
    get 'questions/universities/:university', to: 'questions#show_from_university', as: 'show_questions_in_university'
  end

  namespace :questions do 
    #necessary to pass the domain and course params as they are, otherwise queensu.ca will be passed as queenu only, this constraint escapes special chars.
    constraints course: /[\S\s]+/, university: /[\S\s]+/ do
      get 'unanswered/:course', to: 'unanswered#index', as: 'unanswered'
    end
  end

end

app/models/group.rb
class Group < ApplicationRecord
  include GroupMethods

  belongs_to :creator, class_name: 'User', required: true
  belongs_to :university, foreign_key: 'university_domain', required: true
  belongs_to :course, foreign_key: [:course_name, :university_domain], required: true
  
  has_many :group_enrollments, dependent: :destroy
  has_many :users, through: :group_enrollments
  has_many :comments, dependent: :destroy

  validates :title, :description, :starts_at, :ends_at, :location, :status, presence: true
  validates :seats, numericality: { only_integer: true, greater_than: 1 }
  validate  :ends_at_greater_than_starts_at, if: lambda{|object| object.errors.empty?}

  def cancel!
    update!(status: 'cancelled')
  end

  private

    def ends_at_greater_than_starts_at
      if starts_at >= ends_at
        errors.add(:ends_at, "Must be greater than start time")
      end
    end
end

app/controllers/groups/cancelations_controller.rb
class Groups::CancelationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group
  before_action :authorize

  def cancel
    @group.cancel!
    respond_to do |format|
      format.html { redirect_to @group, notice: 'Group was cancelled. Please leave a comment to let other students know' }
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def authorize
    unless current_user == @group.creator
      flash[:alert] = "You are not allowed to edit someone else's group."
      redirect_to @group
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :show_from_my_university]
  before_action :set_group, only: [:edit, :update]
  before_action :authorize, only: [:edit, :update]
  before_action :check_if_cancelled, only: [:edit, :update]
  before_action :set_autocomplete, only: [:new, :create]

  def index
    #GroupIndex is a SQL view, defined in db/views
    @groups = GroupIndex.paginate(per_page: 5, page: params[:page]).includes(:creator)
    @universities = University.universities_that_have_groups
  end

  def show
    @group = GroupShow.find(params[:id])
    @attendees = User.where(id: @group.attendees)
    @comments = @group.comments.includes(:user).order('id ASC')
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    #courses are unique
    course = Course.where(
      name: params[:course_name].upcase.strip.gsub(/ +/,""),
      university_domain: params[:university_domain],
    ).first_or_create

    @group = course.groups.new(group_params)
    @group.creator = current_user
    @group.status = 'active'
    
    respond_to do |format|
      if @group.save
        #enroll the creator in the group 
        GroupEnrollment.create!(user: current_user, group: @group)
        format.html { redirect_to @group, notice: 'Group was successfully published.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: "Group successfully updated." }
      else
        format.html { render :edit }
      end
    end
  end

  def show_from_course
    @course = Course.find(params[:course])
    @university = @course.university
    @groups = @course.group_indices.paginate(per_page: 5, page: params[:page]).includes(:creator)
    render :show_with_course
  end

  def show_from_my_university
    @university = current_user.university
    @groups = @university.group_indices.paginate(per_page: 5, page: params[:page]).includes(:creator)
    @courses = Course.joins(:groups).where(university_domain: @university.domain).distinct
    render :show_from_university
  end

  def show_from_university
    @university = University.find(params[:university])
    @courses = Course.joins(:groups).where(university_domain: @university.domain).distinct
    @groups = @university.group_indices.paginate(per_page: 5, page: params[:page]).includes(:creator)
  end

  private

    def set_autocomplete
      @university = current_user.university
      @courses    = @university.courses.pluck(:name)
    end

    def group_params
      params.require(:group).permit(:seats, :location, :starts_at, :ends_at, :title, :description)
    end

    def set_group
      @group = Group.find(params[:id])
    end

    def authorize
      unless @group.creator_id == current_user.id
        flash[:alert] = "You are not allowed to edit someone else's group."
        redirect_to @group
      end
    end

    def check_if_cancelled
      unless @group.active?
        flash[:alert] = "You are not allowed to edit cancelled or completed groups"
        redirect_to @group
      end
    end
  
end

app/views/groups/_form.html.haml
=fields_for :group do |g_fields|
  =label_tag 'Title'
  %br
  =g_fields.text_field :title, class: 'form-control', placeholder: "Enter a title for the group (e.g. Exam review session)"
  %br
  =label_tag 'Description'
  %br
  =g_fields.text_area :description, class: 'form-control', placeholder: "Enter a discription (e.g. Hi friends, let's meet and prepare for the test together, we can review chapter 1 and 2 and do previous tests"
  %br
  =label_tag 'Start Time'
  %br
  =g_fields.text_field :starts_at, class: 'datepicker form-control'
  %br
  =label_tag 'End Time'
  %br
  =g_fields.text_field :ends_at, class: 'datepicker form-control'
  %br
  =label_tag 'Seats'
  %br
  =g_fields.text_field :seats, class: 'form-control', placeholder: 'Enter the number of seats including you, minimum 2'
  %br
  =label_tag 'Location'
  %br
  =g_fields.text_field :location, class: 'form-control', placeholder: "Enter the location where you will meet (e.g. Public Library, Room 232)"

app/views/groups/_group.html.haml
.link
  .card.frow.bottom-space
    .profile-pic.size-30px
      =render 'partials/profile_picture', user: group.creator, size: :small
    .fcol
      .frow.bottom-space
        %h4.title
          =link_to("#{group.title}", group_path(group))

      .frow
        .tags
          =link_to("#{group.university_name}", show_groups_in_university_path(group.university_domain), class: "btn btn-xs btn-info", role: "button")
          =link_to("#{group.course_name}", show_groups_in_course_path("#{group.course_name},#{group.university_domain}"), class: "btn btn-xs btn-info", role: "button")
          - if group.cancelled?
            %span.label.label-danger.btn-xs
              Cancelled
          - elsif group.active?
            %span.label.label-success.btn-xs
              Available Seats:
              = group.available_seats
          -else 
            %span.label.label-default.btn-xs
              Completed
      .attendees-count
        - attendees_count = group.num_attendees
        = "#{attendees_count} #{"Student".pluralize(attendees_count)} #{group.active? ? 'going' : 'went'} "

app/views/groups/_group_card.html.haml
.card.frow.header
  %h4.title
    =@group.title
  .time.grey
    =local_relative_time(@group.created_at, type: 'time-or-date')

.card.frow-group.main
  .fcol
    .frow
      %i.fa.fa-clock-o.date-time
        %span.group-date
          =@group.starts_at.strftime("%A, %B %d, %Y")
        %p.group-time
          ="#{@group.starts_at.strftime("%I:%M %p")} to #{@group.ends_at.strftime("%I:%M %p")}"
      - if @group.cancelled?
        .cancelled
          %span.label.label-danger.btn-xs
            Cancelled
      - elsif @group.completed?
        .completed
          %span.label.label-default.btn-xs
            Completed
          
    .frow.place
      %i.fa.fa-map-marker
        %span.location
          =@group.location

    .frow.description
      %i
        =@group.description
    
    .frow.bottom-space
      .tags
        =link_to("#{@group.university_name}", show_groups_in_university_path(@group.university_domain), class: "btn btn-xs btn-info", role: "button")
        =link_to("#{@group.course_name}", show_groups_in_course_path("#{@group.course_name},#{@group.university_domain}"), class: "btn btn-xs btn-info", role: "button")
        
    .frow
      .likeable-owner
        - if @group.creator_id
          %span.grey created by:
          =link_to(" " + @group.username, user_path(@group.creator_id))
          %i.fa.fa-trophy.fa-lg.left-space
          ="+" + @group.user_score.to_s

    -if user_signed_in? && current_user.id == @group.creator_id && @group.active?
      .frow
        .edit-post
          =link_to("Edit", edit_group_path(@group))
          =link_to("Cancel", cancel_groups_cancelation_path(@group), method: :patch, data: { confirm: 'Are you sure you want to cancel this group?' })

  - if user_signed_in?
    = render 'group_enrollments/enrollment'

  %h3
    = "Students #{@group.active? ? 'going' : 'went'} :"
    .frow.attendees
      -@attendees.each do |u|
        = render 'group_enrollments/attendee', u: u
 
  - unless user_signed_in?
    .login-to-join
      Sign in to attend this group.


.container
  #myModal.modal.fade{:role => "dialog"}
    .modal-dialog
      .modal-content
        .modal-header
          %h4.modal-title
            .alert.alert-success
              Success. You have been added to the list of students attending this group.
        .modal-footer
          =link_to 'Add to Calendar', "https://www.google.com/calendar/render?action=TEMPLATE&text=#{@group.title}&dates=#{@group.starts_at.strftime('%Y%m%d')}T#{@group.starts_at.strftime('%H%M%S')}/#{@group.ends_at.strftime('%Y%m%d')}T#{@group.ends_at.strftime('%H%M%S')}&location=#{@group.location}", class: "btn btn-primary", target: :_blank

          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/groups/edit.html.haml
.group-form
  %h4 Edit Group
  -if @group.errors.any?
    %ul.alert.alert-danger
      .container
        -@group.errors.full_messages.each do |msg|
          %li
            =msg
=form_tag(group_path(@group), method: :put, class: 'form-group') do
  =render 'groups/form'
  %br
  =submit_tag 'Update Group', class: 'btn btn-primary'

app/views/groups/index.html.haml
%h4 Universities
.frow
  %span.universities
    -@universities.each do |u|        
      =link_to("#{u.name}", show_groups_in_university_path(u.id) , class: "btn btn-xs btn-info", role: "button")
  .new-group-button
    =link_to 'New Group', new_group_path, class: 'btn btn-primary'

%h4 Groups

=render partial: 'groups/group', collection: @groups
=will_paginate @groups, renderer: BootstrapPagination::Rails

app/views/groups/new.html.haml
.group-form
  %h4 New Study Group
  -if @group.errors.any?
    %ul.alert.alert-danger
      .container
        -@group.errors.full_messages.each do |msg|
          %li
            =msg
  =form_tag(groups_path, method: :post, class: 'form-group') do
    =label_tag 'University'
    %br
    //preselected university: on new page, it's the current user's university, on re-render after validation fails, it's the groups university 
    =select_tag :university_domain, options_from_collection_for_select(University.all, "domain", "name",@group.try(:university_domain) || @university.domain), class: 'form-control', id: 'university_select'
    %br
    =label_tag 'Course'
    %br
    =text_field_tag :course_name, nil, class: 'typeahead form-control', autocomplete: 'off', placeholder: "Enter a course name and number without spaces or special characters (e.g. HIST121) ... ", id: 'group_courses', data: { autocomplete_course: @courses }
    %br
    =render 'groups/form'
    %br
    =submit_tag 'Publish Group', class: 'btn btn-primary'

app/views/groups/show.html.haml
.group-show
  = render 'groups/group_card'
  .comments
    .ExistingComments
      =render @comments
  - if user_signed_in?
    =render 'comments/form', path: group_comments_path(@group), verb: :post

app/views/groups/show_from_university.html.haml
%h3
  =@university.name
.frow
  %span.courses
    %h4 Courses
    -@courses.each do |c|
      =link_to("#{c.name}", show_groups_in_course_path(c), class: "btn btn-xs btn-info", role: "button")
  .new-group-button
    =link_to "New Group", new_group_path, class: 'btn btn-primary'
%h4 Groups

=render partial: 'groups/group', collection: @groups
=will_paginate @groups, renderer: BootstrapPagination::Rails

app/views/groups/show_with_course.html.haml
.frow.subheader
  .info
    %h4
      =@course.name
      %br
      %small
        =@university.name
  .new-group-button
    =link_to 'New Group', new_group_path, class: 'btn btn-primary'

=render partial: 'groups/group', collection: @groups
=will_paginate @groups, renderer: BootstrapPagination::Rails