config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  #######API#########
  #https::/api.coursemate.io/v1/users

  constraints subdomain: 'api' do 
    namespace :api, defaults: {format: :json}, path: '/' do         
      namespace :v1 do
        resources :auth_tokens, only: [:create]
        resources :users, only: [:index]
      end
    end
  end

  authenticated :user do
    root "groups#show_from_my_university", as: :authenticated_root
  end

  root "groups#index"

  devise_for :users, :path => 'account', :path_names => { :edit => "edit_account" }

  # SIDEKIQ
  authenticate :user, lambda { |u| u.is_master? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  get 'account/edit_profile', to: 'users#edit'

  resources :users, only: [:index, :show, :update] do 
    member do 
      get 'questions'
      get 'answers'
      get 'groups'
    end
  end

  resources :notifications, only: [:index] do
    member do
      patch 'mark_read'
    end
    collection do
      get 'top_notifications'
    end
  end

  resources :questions, shallow: true do
    resources :comments, except: [:new, :show]
    resources :answers, except: [:new, :show]
    member do 
      delete 'likes', to: 'likes#destroy', defaults: { type: "question" }
      post 'likes', to: 'likes#create', defaults: { type: "question" }
    end
  end

  resources :course_auto_completes, only: [:index]

  resources :answers, only: [], shallow: true do
    resources :comments, except: [:new, :show]
    member do 
      delete 'likes', to: 'likes#destroy', defaults: { type: "answer" }
      post 'likes', to: 'likes#create', defaults: { type: "answer" }
    end
  end

  resources :groups, shallow: true do 
    resources :comments, except: [:new, :show]
    member do
      delete 'enrollments', to: 'group_enrollments#destroy'
      post 'enrollments', to: 'group_enrollments#create'
    end
  end

  namespace :groups do 
    resources :cancelations, only: [] do 
      member do 
        patch 'cancel'
      end
    end
  end

  get 'subscriptions/:id/unsubscribe', to: 'subscriptions#unsubscribe', as: 'unsubscribe', id: "{{SECRET_TOKEN}}"

  resources :user_courses, only: [:create, :destroy]

  constraints course: /[\S\s]+/, university: /[\S\s]+/ do #necessary to pass the domain and course params as they are, otherwise queensu.ca will be passed as queenu only, this constraint escapes special chars.
    get 'groups/courses/:course', to: 'groups#show_from_course', as: 'show_groups_in_course'
    get 'questions/courses/:course', to: 'questions#show_from_course', as: 'show_questions_in_course'
    get 'groups/universities/:university', to: 'groups#show_from_university', as: 'show_groups_in_university'
    get 'questions/universities/:university', to: 'questions#show_from_university', as: 'show_questions_in_university'
  end

  namespace :questions do 
    #necessary to pass the domain and course params as they are, otherwise queensu.ca will be passed as queenu only, this constraint escapes special chars.
    constraints course: /[\S\s]+/, university: /[\S\s]+/ do
      get 'unanswered/:course', to: 'unanswered#index', as: 'unanswered'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  def to_param
    "#{id}-#{username.parameterize}"
  end

  MAX_AVATAR_UPLOAD_SIZE_MB = 10.freeze
  DIRECT_UPLOAD_URL_FORMAT = %r{\Ahttps:\/\/#{ENV['S3_BUCKET_CACHE_NAME']}\.s3\.amazonaws\.com\/.*\.(jpg|jpeg|JPG|JPEG)(\?transform=[0-9a-z\-]+)?\z}.freeze

  devise :database_authenticatable, :registerable, :confirmable, 
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  has_many :questions
  has_many :question_indices, foreign_key: [:user_id]
  has_many :answers
  has_many :comment_statuses, dependent: :destroy

  has_many :comments
  has_many :likes
  has_many :group_enrollments
  has_many :group_indices, through: :group_enrollments
  has_many :notification_lists, foreign_key: 'notified_user'
  has_many :courses, class_name: 'UserCourse'
  belongs_to :university, foreign_key: 'university_domain'

  validates :username, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A[a-zA-Z0-9]+\Z/,
    message: "only allows letters (a-z) and numbers" }
  validate :valid_university_email, if: Proc.new{|object| object.errors.empty?}
  validates :avatar_temp, allow_blank: true, format: { with: DIRECT_UPLOAD_URL_FORMAT }
  
  before_create :set_university
  after_commit :enqueue_image, on: :update

  # override the send_devise_notification to use ActiveJob
  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  def self.with_score
    User.joins("left join (select questions.user_id, count(*) * 5 as question_likes_score from likes 
      join questions on likes.question_id = questions.id 
      group by questions.user_id) t1
    on t1.user_id = users.id 
    left join 
     (select answers.user_id, count(*) * 10 as answer_likes_score from likes 
      join answers on likes.answer_id = answers.id 
        group by answers.user_id) t2
    on t2.user_id = users.id").select("users.*, COALESCE(COALESCE(t1.question_likes_score, 0) + COALESCE(t2.answer_likes_score, 0), 0) as score")
  end

  def is_ambassador?
    privileges >= 1
  end

  def is_admin?
    privileges >= 2
  end

  def is_master?
    privileges >= 3
  end

  def unread_notifications_count
    0
  end

  def questions_he_answered
    QuestionIndex.joins(:answers).where(answers: { user_id: self.id} ).distinct
  end  

  def unread_notification_count
    notification_lists.where(seen: false).count
  end


  private

    def find_university_with_domain
      #user sign up
      @university ||= University.where(" ? LIKE CONCAT('%@', domain) ", self.email).first
    end

    def valid_university_email
      unless find_university_with_domain
        errors.add(:email, "is not a valid university email")
      end
    end

    def set_university
      self.university = find_university_with_domain
    end

    def enqueue_image
      if avatar_temp.present?
        update_column(:processing_avatar, true)
        AvatarWorker.perform_async(id)
      end
    end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApiBaseController
  before_action :authenticate_api_user!

  def index
    render json: { api: true}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_current_user, only: [:edit, :update]

  def index
    @users = User.with_score.all
  end

  def show
    @user = User.with_score.find(params[:id])
    @questions = @user.question_indices.limit(5).includes(:user)
    @questions_he_answered = @user.questions_he_answered.limit(5).includes(:user)
    @groups = @user.group_indices.limit(5).includes(:creator)
    @courses = @user.courses
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_path(@user), notice: "Profile successfully updated." }
      else
        format.html { render :edit }
      end
    end
  end

  def questions
    @user = User.find(params[:id])
    @questions = @user.question_indices.paginate(per_page: 5, page: params[:page]).includes(:user)
  end

  def answers
    @user = User.find(params[:id])
    @questions = @user.questions_he_answered.paginate(per_page: 5, page: params[:page]).includes(:user)
  end

  def groups
    @user = User.find(params[:id])
    @groups = @user.group_indices.paginate(per_page: 4, page: params[:page]).includes(:creator)
  end

  private

    def user_params
      params.require(:user).permit(:username, :first_name, :last_name, :about_me, :avatar_temp, :crop_x, :crop_y, :crop_w, :crop_h)
    end

    def set_current_user
      @user = current_user
      @s3_direct_post = S3_BUCKET.presigned_post(
        key: "uploads/#{Time.now.to_i}-#{SecureRandom.hex}/${filename}",
        success_action_status: '201',
        content_length_range: 0..User::MAX_AVATAR_UPLOAD_SIZE_MB*1024**2,
        acl: 'public-read'
      )
    end

end

app/views/users/_user_course_form.html.haml
=form_tag(user_courses_path, method: :post, remote: true, class: 'form-group form-inline', id: 'user-course-form', style: 'display:none') do
  %span.course-name-input
    =text_field_tag :course_name, nil, class: 'form-control', placeholder: "e.g. CISC121",pattern: "[A-Za-z0-9 ]{2,}", title: 'Only letters and numbers, at least two characters', required: 'true'

  =submit_tag 'Done', class: 'btn btn-xs btn-primary'

  %span.help-block.has-error.errors

app/views/users/answers.html.haml
%h4
  = "#{@user.username}'s Answers" 
=render partial: 'questions/question', collection: @questions
=will_paginate @questions, renderer: BootstrapPagination::Rails

app/views/users/edit.html.haml
.user-edit.center-block
  #crop-modal.modal{tabindex: "-1", role: "dialog", aria_labelledby: "crop image dialog"}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{type: "button", class: "close", aria_label: 'Close', data: {dismiss: "modal"}}
            %span{aria_hidden: "true"} &times;
          %h2.modal-title 
            Crop your profile picture
        .modal-body
          =image_tag("", id: "cropbox", alt: t('main.profile_pic_alt'))
        .modal-footer
          %button.btn.btn-default{type: "button", data: {dismiss: "modal"}} 
            Cancel
          %button.btn.btn-primary#confirm-avatar{type: "button", data: {dismiss: "modal"}} 
            OK

  .form
    %h1
      Profile Settings
    #s3-direct-post{data: {url: "#{@s3_direct_post.url}", fields: "#{@s3_direct_post.fields.to_json}", max_upload_size_mb: User::MAX_AVATAR_UPLOAD_SIZE_MB}}
    = simple_form_for @user, html: { class: "directUpload" } do |f|
      = f.error_notification
      .form-group
        .image-upload
          #preview-container.profile-pic.size-50px
            - if @user.processing_avatar || (@user.avatar_temp_changed? && @user.avatar_temp.present?)
              - transform = URI.parse(@user.avatar_temp).query.present? ? CGI.parse(URI.parse(@user.avatar_temp).query)['transform'][0] : nil
              #unprocessed-preview.hidden{data: {url: @user.avatar_temp, transform: transform}}
            - else
              = render 'partials/profile_picture', user: @user, size: :small
          .btn.btn-primary.fileinput-button
            %input{type: "file", name: "avatar_temp", id: "upload-input", accept: "image/*"}
              %span#upload-text
                Upload
      %p.upload-errors.errors
        - if @user.errors[:avatar_temp].any?
          profile picture uploads must be jpg/jpeg files less than 2MB
      = f.input :avatar_temp, as: :hidden, input_html: { id: 'avatar-field' }
      = f.input :username, placeholder: "Username"
      = f.input :first_name, placeholder: "First name"
      = f.input :last_name, placeholder: "Last name"
      = f.input :about_me, placeholder: "Tell other students a bit about you, year of study, major, etc.."
      - %w[x y w h].each do |attribute|
        = f.input "crop_#{attribute}", as: 'hidden'
      = f.button :submit, 'Update Profile', id: 'submit-button'

app/views/users/groups.html.haml
%h4
  = "#{@user.username}'s Groups" 
=render partial: 'groups/group', collection: @groups
=will_paginate @groups, renderer: BootstrapPagination::Rails

app/views/users/index.html.haml
.user-index
  %h4 Users
  .frow.users
    -@users.each do |u|
      .card.frow
        .profile-pic.size-30px
          = render 'partials/profile_picture', user: u, size: :small
        .user
          =link_to u.username, user_path(u)
          %i.fa.fa-trophy.fa-lg
          ="+" + u.score.to_s
      

app/views/users/questions.html.haml
%h4
  = "#{@user.username}'s Questions" 
=render partial: 'questions/question', collection: @questions
=will_paginate @questions, renderer: BootstrapPagination::Rails

app/views/users/show.html.haml
.user-show
  .profile-info
    .container
      .row 
        .col-sm-4.col-md-3
          %h1
            .profile-pic.size-200px
              - if @user == current_user
                = link_to account_edit_profile_path do
                  .link{data: {toggle: "tooltip", placement:"bottom"}, title: 'Change your picture'}
                    = render 'partials/profile_picture', user: @user, size: :large
              - else
                = render 'partials/profile_picture', user: @user, size: :large
        .col-sm-6.col-md-4
          %h1
            -if @user.first_name.nil? or @user.first_name.blank?
              =@user.username
            -else
              =@user.first_name
              =@user.last_name
              %br
              %small
                =@user.username

          .score
            %i.fa.fa-trophy.fa-lg
            %span
              ="+" + @user.score.to_s

          %h2
            =@user.university.name
          %h4
            =@user.about_me
        .col-sm-2.col-md-4
          %h3 
            Courses
            -if @user == current_user
              %i.fa.fa-question{data: {toggle: "tooltip", placement:"right", title: 'We will use these courses to let you know when there are groups or questions for them.'}}
          =link_to "Add", '#', id: "edit-courses-list", remote: true if @user == current_user
          .courses
            .container
              .row
                -@courses.each_slice(4) do |s|
                  .col
                    - s.each do |course|
                      =render 'user_courses/user_course', user_course: course

            %br
            =render 'user_course_form'
              


%div
  %ul.nav.nav-tabs{role: "tablist"}
    %li.active{role: "presentation"}
      %a{"aria-controls": "questions", "data-toggle": "tab", href: "#user-questions", role: "tab" } Questions
    %li{role: "presentation"}
      %a{"aria-controls": "answers", "data-toggle": "tab", href: "#user-answers", role: "tab"} Answers
    %li{role: "presentation"}
      %a{"aria-controls": "groups", "data-toggle": "tab", href: "#user-groups", role: "tab"} Groups

  / Tab panes
  .tab-content
    #user-questions.tab-pane.active{role: "tabpanel"}
      =render partial: 'questions/question', collection: @questions
      - if @questions.size == 5
        =link_to("All Questions", questions_user_path(@user))

    #user-answers.tab-pane{role: "tabpanel"} 
      =render partial: 'questions/question', collection: @questions_he_answered
      - if @questions_he_answered.size == 5
        =link_to("All Answers", answers_user_path(@user))
    #user-groups.tab-pane{role: "tabpanel"} 
      =render partial: 'groups/group', collection: @groups
      - if @groups.size == 5
        =link_to("All Groups", groups_user_path(@user))